server.port=8001
spring.application.name=msvc-usuario

spring.datasource.url=jdbc:postgresql://localhost:5432/pichangapp_usuarios
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

config.security.oauth.jwt.key=clave_secreta_super_segura_para_pichangapp_jwt_2026
