spring.application.name=msvc-match
server.port=8082

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pichangapp_matches
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
