# 1. nombre y un puerto específico para que no choque con los otros
spring.application.name=msvc-seguridad
server.port=8004

# 2. Credenciales de base de datos en la nube (Supabase)
# Usando pooler IPv4 global para evitar fricciones de DNS en el equipo
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?options=-c%20search_path=public
spring.datasource.username=postgres.pqukomxvkdmxceywkltx
spring.datasource.password=pichangapp4thewin

# 3. Configuración de Hibernate (para no escribir SQL ahora)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# RabbitMQ Config (CloudAMQP)
spring.rabbitmq.addresses=amqps://lbxulfmr:93xsvsKPGMXSxipjnQMhumxLMeZ0uR2C@shark.rmq.cloudamqp.com/lbxulfmr