# 1. nombre y un puerto específico para que no choque con los otros
spring.application.name=msvc-seguridad
server.port=8004

# 2. Credenciales de base de datos local x ahora (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/pichangapp_db
spring.datasource.username=postgres
spring.datasource.password=pichangapp4thewin

# 3. Configuración de Hibernate (para no escribir SQL ahora)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true